# Numpy Tutorial

#  1)  N-dimensional Array (ndarray Object)

ndarray is an multidimensional container which can contain only homogeneous items.
The shape of such an array is defined by the 'shape' attribute. The data type of the items inside a ndarray is stored in an object known as 'dtype'.

The following code snippet allows us to make a 2-dimensional array or a matrix of size 2X2.

The shape can be easily retrieved using the command 'obj_name'.shape

The data type of all elements can be easily retrieved using the command 'obj_name'.dtype

In [2]:
import numpy as np

In [8]:
X=np.array([[1,2],[2,3]])
print('X :\n', X)

X :
 [[1 2]
 [2 3]]


In [14]:
X3=np.array([[2,6,7],[8,5,7],[6,8,3]])
print(X3[1][2])

7


In [15]:
X3

array([[2, 6, 7],
       [8, 5, 7],
       [6, 8, 3]])

# rows and column distribution in array
[[2(0,0), 6(0,1), 7(0,2)],

 [8(1,0), 5(1,1), 7(1,2)],
 
 [6(2,0), 8(2,1), 3(2,2)]]

In [16]:
# The shape attribute returns the shape of numpy array as a tuple
X3.shape

(3, 3)

In [17]:
# The total number of elements of the array is returned by size
X3.size

9

In [18]:
# The number of axes (dimensions) of the array
X3.ndim

2

In [19]:
X3.dtype

dtype('int32')

# 2)  Making a ndarray object

np.zeros

np.zeros :- Creates numpy array of given size and given type initialized with zeros.

In [22]:
x=np.zeros(shape=(2,3),dtype=float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Create a 3 * 3 n-dim array with 3 numbers from np.zeros.
x1=np.zeros(shape=(3,3), dtype=float)
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3. Accessing array elements
3.1 Basic Indexing (returns view)

Accessing the array elements through basic indexing

In [25]:
x=np.arange(50,100)
x

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
x[5]

55

Accessing the elements on skipping 3 elements

In [30]:
print('x[5:40:3]=',x[5:40:3])

x[5:40:3]= [55 58 61 64 67 70 73 76 79 82 85 88]


Fetching elements based on a specific index to end

In [31]:
print('x[30:]=',x[30:]) 

x[30:]= [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Create an array of 10 numbers and slice it to print 5th,7th,9th element from the start 
Do the same using negative indexing

In [33]:
x1[20:30:1]
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3.2 Making copies of numpy array object
To create one or more references to the existing numpy array object , 
the assignment operator can be used.

Once another reference of an existing array object is created, 
any change made to the array through new reference affects the original contents of the array.

In [39]:
arr1=np.array([1,2,3,4])
print("Contents of the original array :",arr1)
ref_arr=arr1
# Change ndarray contents through reference array
ref_arr[2]=6
print("Contents of the referenced array :",ref_arr)

Contents of the original array : [1 2 3 4]
Contents of the referenced array : [1 2 6 4]


We can observe that if changes are made to the referenced array, 
the changes are being reflected to the original array as well.

Creating a deep copy using the copy() method

In [43]:
original_array=np.array([12,49,24,64,80,56,76])
print('original_array=',original_array)
#copying elements from original array to original array copy
original_array_copy=original_array.copy()
original_array_copy[1]=16
original_array_copy[2]=59
original_array_copy[5]=34
print('original_array_copy=',original_array_copy)

original_array= [12 49 24 64 80 56 76]
original_array_copy= [12 16 59 64 80 34 76]


In [44]:
original_array_copy.shape

(7,)

In [54]:
# Consider X
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(x)
# 1. Construct the following 2-D array from contents of 'X':
Y=np.array[[x[0, 0], x[0, 1]],[x[2, 2], x[2, 2]]]
print(X)
# 2. Create a copy of the above array using assignment opertor and changes the values in index(3,1) to 
# 14 and see the changes.
Y_copy=Y.copy()
print(Y_copy)


# 3. Use deep copy method using slice and copy() function and copy the original elements of the array.
# Make changes to index(2,3) to 10 and check the changes.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
X_copy[0,1]=44
print(X_copy)